[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Variables de entorno para el build (estas deben configurarse también en el panel de Netlify)
[context.production.environment]
  VITE_SUPABASE_URL = "https://jgnimjsnshjnpycjckje.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnbmltanNuc2hqbnB5Y2pja2plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1Mzc2NDksImV4cCI6MjA3NzExMzY0OX0.mOJQqhWhYymifa6pBpWCCjqNVydKKYhBP1GCrAe1-_0"